#!/usr/bin/env python3
"""InterfaceSpec v0 loader: interfacespec-v0.yaml -> d1laws role/law rows.

Emits SQL INSERTs into d1_role and d1_law (the tables role_tables.sql
fills by hand).  Validates the spec against itself (every role, protocol,
value source, kind/relation is declared); d1laws itself is not touched.

The only d1-specific knowledge here is how d1 encodes a law in its jsonb
params (ENCODE below).
"""
import json
import sys

import yaml

SOURCE = {'support_proc': 'proc', 'strategy': 'op', 'operator': 'op'}

# How d1 stores the relation of each kind in params.  K3/K5/K6 have one
# relation each, fixed by the engine; K4 "image_equal" is consequence=image.
ENCODE = {
    'K1': lambda rel: {'property': rel},
    'K2': lambda rel: {'relation': rel},
    'K3': lambda rel: {},
    'K4': lambda rel: {'consequence': 'image'} if rel == 'image_equal' else {},
    'K5': lambda rel: {},
    'K6': lambda rel: {},
}
# value sources that the d1 engine takes from params; the rest are implied by the kind
SOURCE_PARAM = {'completions': ('source', 'ternary_completions')}
CONSTANTS = ('seed', 'iff')


def fail(msg):
    sys.exit('interfacespec-v0: ' + msg)


def lit(v):
    if isinstance(v, int) and not isinstance(v, bool):
        return str(v)
    return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"


def translate(spec):
    roles, protocols = spec['roles'], spec['protocols']
    sources, kinds = spec['value_sources'], spec['law_kinds']
    role_rows, law_rows = [], []
    for itf in spec['opclass_interfaces']:
        am = itf['am']
        for b in itf['bindings']:
            if b['role'] not in roles:
                fail(f"{am}: binding of undeclared role {b['role']}")
            if b['protocol'] not in protocols:
                fail(f"{am}: undeclared protocol {b['protocol']}")
            if b['scope'] not in ('am', 'opfamily') or (b['scope'] == 'opfamily') != ('opfamily' in b):
                fail(f"{am}: bad scope for {b['role']}")
            if (b['source'] == 'operator') != ('number' not in b):
                fail(f"{am}: {b['role']}: source operator takes no number, others need one")
            role_rows.append((am, b.get('opfamily'), b['role'], SOURCE[b['source']], b.get('number'),
                              b['protocol'], b.get('selector'), b.get('righttype', 'same')))
        bound = {b['role'] for b in itf['bindings']}
        for law in itf['laws']:
            k, rel = law['kind'], law['relation']
            if rel not in kinds[k]:
                fail(f"{law['id']}: relation {rel} is not a {k} relation")
            used = list(law['roles'].values()) + [law[x] for x in ('reference', 'guard') if x in law]
            for r in used:
                if r not in bound:
                    fail(f"{law['id']}: role {r} has no binding in {am}")
            params = dict(law['roles'])
            for x in ('reference', 'guard', 'trusted'):
                if x in law:
                    params[x] = law[x]
            params.update(ENCODE[k](rel))
            for vs in law['value_source']:
                if vs not in sources:
                    fail(f"{law['id']}: undeclared value source {vs}")
                if vs in SOURCE_PARAM:
                    params[SOURCE_PARAM[vs][0]] = SOURCE_PARAM[vs][1]
            for c in CONSTANTS:
                if c in law:
                    params[c] = law[c]
            law_rows.append((am, law.get('opfamily'), law['id'], k, json.dumps(params, sort_keys=True)))
    return role_rows, law_rows


def main():
    spec = yaml.safe_load(open(sys.argv[1]))
    if spec.get('version') != 'v0':
        fail('not a v0 spec')
    role_rows, law_rows = translate(spec)
    out = ['-- generated by interfacespec/load_v0.py from ' + sys.argv[1].split('/')[-1] + '; do not edit']
    out.append('INSERT INTO d1_role (am, family, role, source, number, protocol, attr, righttype) VALUES')
    out.append(',\n'.join('  (' + ', '.join(lit(v) for v in r) + ')' for r in role_rows) + ';')
    out.append('INSERT INTO d1_law (am, family, law, kind, params) VALUES')
    out.append(',\n'.join('  (' + ', '.join(lit(v) for v in r) + ')' for r in law_rows) + ';')
    if '--vocab' not in sys.argv:
        print('\n'.join(out))
        return
    # role shapes and protocol names, to compare with the engine's own vocabulary
    out.append('CREATE TEMP TABLE spec_role_vocab (role text, shape text);')
    out.append('INSERT INTO spec_role_vocab VALUES ' +
               ', '.join(f'({lit(r)}, {lit(s)})' for r, s in spec['roles'].items()) + ';')
    out.append('CREATE TEMP TABLE spec_protocol (protocol text);')
    out.append('INSERT INTO spec_protocol VALUES ' + ', '.join(f'({lit(p)})' for p in spec['protocols']) + ';')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
